# Site settings
title: "Vibe Coding Playbook"
description: "Let's Do It Right - A comprehensive guide to AI-assisted development"
author: "Sam Fernando"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages settings
url: "https://samfernandoau.github.io"  # Replace with your GitHub username
baseurl: "/VibeCodingPlaybook"     # Replace with your repository name

# Navigation
header_pages:
  - index.md
  - whats-vibe-coding.md
  - common-habits.md
  - best-practices.md
  - enterprise-alignment.md
  - adoption-framework.md
  - references.md